### ISSUE TITLE
DIRECTORY.md file missing in a few repositories

### ISSUE THREAD

**Issue by Panquesito7** [TheAlgorithms/website#1]
In the repositories section, I don't see all algorithm-repositories there.
For example, the MATLAB-Octave repository is missing from the list.

**Comment by maltejur** [comment]
All these repositories are missing the DIRECTORY.md file that is currently used for parsing the algorithms

Complete list repos that still need a DIRECTORY.md file:

- [x] F-Sharp
- [x] Rust
- [x] AArch64_Assembly
- [x] C-Sharp
- [x] R
- [x] PHP (wrong formatting)
- [x] Kotlin
- [x] Scala
- [x] Jupyter
- [x] Haskell (wrong formatting)
- [x] OCaml
- [x] Swift (empty)
- [x] Elm
- [x] MATLAB-Octave

The solution I am probably going to do is manually adding DIRECTORY.md files to all these repos. Help would also be appreciated for that.

**Comment by maltejur** [comment]
But first I will rewrite the parsing script so that the data read out of the DIRECTORY.md files is consistent.

**Comment by Panquesito7** [comment]
I will try to make a PR for those repositories to add `DIRECTORY.md`.
In the [C++](https://github.com/TheAlgorithms/C-Plus-Plus) repository, there's a GitHub workflow that adds current algorithms on `DIRECTORY.md`. You can see that file and try to implement it. 🙂

**Comment by Panquesito7** [comment]
Now working on it.

**Comment by Panquesito7** [comment]
https://github.com/TheAlgorithms/F-Sharp/pull/14

**Comment by Panquesito7** [comment]
I will continue doing the following with the other repositories. 🙂

**Comment by maltejur** [comment]
Thank you, I will also try to add this workflow to some repos.

**Comment by Panquesito7** [comment]
Nah, it's OK as-is, I can do it. Otherwise, there's this possibility we make a PR in the same repository. 🙂

**Comment by Panquesito7** [comment]
https://github.com/TheAlgorithms/Rust/pull/181

**Comment by Panquesito7** [comment]
https://github.com/TheAlgorithms/AArch64_Assembly/pull/2
Keep an eye for more PRs in the organization.

**Comment by Panquesito7** [comment]
@maltejur done for all listed repositories. I made a PR for each repository; I can merge them all, but let's better wait until the reviewers find no issues in my PRs, and then it can be merged. 🙂

**Comment by maltejur** [comment]
Thanks, I'll leave this open a few days until all PRs get merged

**Comment by Panquesito7** [comment]
This issue can be closed as all PR's have been merged.
You just need to change the listed repo's on the code (**EDIT:** #5). 🙂

_Offtopic_: Please transfer the repository to TheAlgorithms, now that you are a member of the organization.
