### ISSUE TITLE
The website sometimes fails on mobile

### ISSUE THREAD

**Issue by Panquesito7** [TheAlgorithms/website#103]
On mobile, the website is quite slow, and sometimes it just fails and you need to refresh the page.\
That happens only on mobile, though. On my PC it works a bit slow but it's acceptable.

Any reasons why that happens?\
Thanks.

**Comment by maltejur** [comment]
Yes the website is definitely not that great on mobile. I don't have that much time the next two weeks, but I will see if I can do anything about it.
