### ISSUE TITLE
[FEATURE] Add commas between the numbers

### ISSUE THREAD

**Issue by Panquesito7** [TheAlgorithms/website#108]
It would be much easier to read and understand the stars count in the programming languages list. At least for me, it's quite hard to read them, especially if they're over 10k. It's just an idea; it doesn't have to be implemented. 🙂

![image](https://user-images.githubusercontent.com/51391473/128619255-811cf0f4-9695-4491-ac60-bdb451d974c1.png)

Thank you.

**Comment by maltejur** [comment]
Maybe just display 113k instead of 113860?

**Comment by Panquesito7** [comment]
> Maybe just display 113k instead of 113860?

Yep. Something like that would be good. 👍
