### ISSUE TITLE
Same problem with 2 different names

### ISSUE THREAD

**Issue by SpiderMath** [TheAlgorithms/website#119]
### Description of the bug

I was just looking for something I could contribute when I found that there is a problem on converting degrees to radians on the website, implemented in Python (can be seen [here](https://the-algorithms.com/algorithm/radians))
Later when I tried looking for it (to put an implementation in JavaScript) but then I found [this](https://the-algorithms.com/algorithm/radiantodegree), the exact same problem but only implemented in JavaScript, under a slightly different name.

I am not sure how many of such duplicate problems can be found, but I would request:

1. Checking of problems, so that they are confirmed to be non duplicate
2. Merge these 2 problems into a single one (like that needs to be done, since that's what the website is for, providing easy access to algorithms fast and efficiently)

**Comment by maltejur** [comment]
Thanks for reporting this, should be fixed now.
