### ISSUE TITLE
c# repo doesn't contain DIRECTORY.md file anymore

### ISSUE THREAD

**Issue by maltejur** [TheAlgorithms/website#12]
https://github.com/TheAlgorithms/C-Sharp/pull/205
> Remove directory workflow because it includes what it shouldn't (AssemblyInfo, interfaces, tests, etc.) and titles are ugly

The workflow should be reworked. I don't really know how those files work, so I would appreciate it, if you would do that @Panquesito7

**Comment by Panquesito7** [comment]
It isn't the workflow the one that should be reworked, it is the **name of the folders and files**. If you see the [C++](https://github.com/TheAlgorithms/C-Plus-Plus) repository, `DIRECTORY.md` is properly formatted. I'll try to make a PR to improve the file names and the names of the folders. Thank you for reporting, though. 🙂

**Comment by maltejur** [comment]
That's true, and thank you for fixing the folders there. This also is a more general problem, all the different repos have different naming conventions and some just have top level folders like "Algorithms" and "Datastructures", while a lot of the categories are written slightly different, like "Math", "Maths" and "Basic Maths". This is a pretty big thing to do, but I think in the long term we should try to try to normalize the file structure and categories in all the repos, probably in the style of the C++ repo.

**Comment by maltejur** [comment]
Closed in b3c4a6383b475117c2fa1b79ef44ffaa8eb5e7de
