### ISSUE TITLE
Ugly Numbers & Fermat Little Theorem

### ISSUE THREAD

**Issue by SpiderMath** [TheAlgorithms/website#120]
### Description of the content report

Like the previous issue I made, I found 2 more Algorithms being the exact same. This time they were about Ugly Numbers ([Java](https://the-algorithms.com/algorithm/nthuglynumber) implementation & [Python+Dart](https://the-algorithms.com/algorithm/ugly-numbers) implementation) and Fermat's Little Theorem ([Dart](https://the-algorithms.com/algorithm/fermats-little-theorem) implementation & [Python](https://the-algorithms.com/algorithm/fermat-little-theorem) Implementation)

**Comment by maltejur** [comment]
Fixed, thanks!
