### ISSUE TITLE
Better Code Preview on Mobile

### ISSUE THREAD

**Issue by maltejur** [TheAlgorithms/website#123]
The current code preview is pretty clunky on mobile, a solution to that could be a second one specifically for mobile.

The current one one mobile:

![Screenshot_20211024_000504](https://user-images.githubusercontent.com/48161361/138572988-743e1e75-c06c-46e3-8e6b-4ab2ed5c91e5.png)
![Screenshot_20211024_000515](https://user-images.githubusercontent.com/48161361/138572992-ece0cc03-d765-4d03-bbdf-4936e82a864c.png)
![Screenshot_20211024_000524](https://user-images.githubusercontent.com/48161361/138572996-ee9081bf-1340-4cd6-af52-053930358618.png)

@Panquesito7 what do you think of the current code view on mobile, is it okay as it is right now or should it be replaced?

**Comment by Panquesito7** [comment]
Nice catch 👍 yeah, I think it should be improved. Let me know if you need any help. Thanks 😄
