### ISSUE TITLE
Ditch issue templates

### ISSUE THREAD

**Issue by maltejur** [TheAlgorithms/website#131]
### What would you like to share?

@Panquesito7 the whole issue templates seem a bit unnecessary to me. All of the fields except `What would you like to share?` are kinda useless.
![Screenshot_20211104_171742](https://user-images.githubusercontent.com/48161361/140415989-e4dcd874-3a68-4559-b0f5-4e61e73c9607.png)
Can we just revert to how the issue templates worked before where they just added tags to the issue?

**Comment by Panquesito7** [comment]
IMO, the old issue templates are good, but the new ones (issue forms) make the authors submit issues with the required information. Some people just create blank issues which create unnecessary noise for us.

Which option do you prefer:

1. Keep it as-is.
2. Make it like in [**this repository**](https://github.com/web3community/.github/blob/main/.github/ISSUE_TEMPLATE).
3. Adjust it to make it better, shorter, and cleaner.

Let me know what do you think. Thanks. 🙂

**Comment by maltejur** [comment]
> Adjust it to make it better, shorter, and cleaner.

Yeah that sounds good. For example, on the feature request page you would only need one field where you explain the feature and not really more, while on the bug page it absolutely makes sense to have multiple required fields like `Explain your issue`, `Your Browser`, `Screenshots`, etc.

As I said my problem with the current ones was that they just seemed a bit unnecessary to me because the fields didn't really make sense.

**Comment by Panquesito7** [comment]
> > Adjust it to make it better, shorter, and cleaner.
> 
> Yeah that sounds good. For example, on the feature request page you would only need one field where you explain the feature and not really more, while on the bug page it absolutely makes sense to have multiple required fields like `Explain your issue`, `Your Browser`, `Screenshots`, etc.
> 
> As I said my problem with the current ones was that they just seemed a bit unnecessary to me because the fields didn't really make sense.

Alright, I'll work on it later. Thank you! 😄

**Comment by maltejur** [comment]
Thanks
