### ISSUE TITLE
[BUG] Broken links

### ISSUE THREAD

**Issue by siriak** [TheAlgorithms/website#142]
### Description of the bug

Description
Code implementation links of algorithms when opened are giving 404 errors. I observed such behavior for Bubble sort.

Actual behavior
1. Go to https://the-algorithms.com/algorithm/bubble-sort
2. Scroll down to Code Implementation links
3. Click on Java

Actual behavior
4. See Github 404 page (the link is https://github.com/TheAlgorithms/Java/blob/master/Sorts/BubbleSort.java)

Expected behavior
4. Bubble sort page should open (the link is https://github.com/TheAlgorithms/Java/blob/master/src/main/java/com/thealgorithms/sorts/BubbleSort.java)

### Additional information/context

Originally reported here https://github.com/TheAlgorithms/Java/issues/2840

**Comment by maltejur** [comment]
All of those links in the explanations are hardcoded into https://github.com/TheAlgorithms/Algorithms-Explanation, so they would have to be updated there.

**Comment by Tejas-Teju** [comment]
Anyone working on this issue?

**Comment by maltejur** [comment]
The wrong links in https://github.com/TheAlgorithms/Algorithms-Explanation are still there and I currently don't have the time to fix them.

**Comment by mgncodes** [comment]
Hi, I'd like to contribute to this issue. Kindly assign to me. Thanks!

**Comment by maltejur** [comment]
Sure

**Comment by mgncodes** [comment]
Hi @maltejur, I have a doubt. 
The link for code implementation is changed in the issue mentioned by @Panquesito7 , but the PR made in that issue is still not merged, so it is still not updated in [Algorithms-Explanation](https://github.com/TheAlgorithms/Algorithms-Explanation) repo.
Is it like, if the links in Algorithms-Explanation repo is updated, then only the changes in the link will be reflected here? 
Kindly clarify.

**Comment by maltejur** [comment]
As the comment in that PR already says, the pull request only fixed two links, but every java link in that repository is broken. So it would be great to just have another PR in Algorithms-Explanation where all the links are fixed.

**Comment by sambhavsaxena** [comment]
@siriak @maltejur I have the code ready on my fork, raising a PR real quick.

**Comment by riyaz2014** [comment]
I would like to contribute to this issue. kindly assign to me

**Comment by riyaz2014** [comment]
Hello I would like to contribute contribute to this issue. Kindly assign it to me please

**Comment by Panquesito7** [comment]
Closing as this should be fixed upstream at https://github.com/TheAlgorithms/Algorithms-Explanation
