### ISSUE TITLE
[BUG] Shown contributors are wrong

### ISSUE THREAD

**Issue by appgurueu** [TheAlgorithms/website#146]
### Description of the bug

Contributors are wrong, see https://the-algorithms.com/de/algorithm/linked-stack - it shows only a Lua implementation, yet 4 contributors are shown which haven't contributed to the Lua repo at all.

**Comment by Panquesito7** [comment]
Hey there! That's because that's multiple implementations in multiple languages for that algorithm are added, so in total it would be 4 contributors to that algorithm. Correct me if I'm wrong. 🙂

**Comment by appgurueu** [comment]
> Hey there! That's because that's multiple implementations in multiple languages for that algorithm are added, so in total it would be 4 contributors to that algorithm. Correct me if I'm wrong.

Then why doesn't it shown the "other" implementations?

**Comment by Panquesito7** [comment]
> > Hey there! That's because that's multiple implementations in multiple languages for that algorithm are added, so in total it would be 4 contributors to that algorithm. Correct me if I'm wrong.
> 
> Then why doesn't it shown the "other" implementations?

Other implementations of that same algorithm? It'll only display the explanation from the [Algorithms-Explanation](https://github.com/TheAlgorithms/Algorithms-Explanation) repository *if provided*. Aliases will also show one implementation if set in the settings. I hope I get to understand. :)

**Comment by appgurueu** [comment]
> > > Hey there! That's because that's multiple implementations in multiple languages for that algorithm are added, so in total it would be 4 contributors to that algorithm. Correct me if I'm wrong.
> > 
> > 
> > Then why doesn't it shown the "other" implementations?
> 
> Other implementations of that same algorithm? It'll only display the explanation from the [Algorithms-Explanation](https://github.com/TheAlgorithms/Algorithms-Explanation) repository _if provided_. Aliases will also show one implementation if set in the settings. I hope I get to understand. :)

![Bildschirmfoto von 2021-12-24 20-56-29](https://user-images.githubusercontent.com/34514239/147370862-12418de7-2afb-4dc5-bec5-317c24a43e25.png)

This is what it currently looks like. Indisputably misleading.

**Comment by maltejur** [comment]
Yeah that is not what it should look like, I'll look into it

**Comment by maltejur** [comment]
Ok funny thing there actually once existed a `linked_stack.py` which later got renamed to `stack_with_singly_linked_list.py`.

![image](https://user-images.githubusercontent.com/48161361/147372063-2fa8e8e6-5d73-4ec7-b852-173cd0c6ce21.png)
![image](https://user-images.githubusercontent.com/48161361/147372075-d30d0719-b9a8-43f4-b290-7a82d11c55c2.png)

But the previous commits of course still got counted for `linked_stack.py` so here they are. I would argue that this is such a niche problem that it isn't worth looking into more, especially with the possible changes planned to the website which we discussed in the discord.
