### ISSUE TITLE
[CONTENT] JavaScript Singly Linked List not listed on website?

### ISSUE THREAD

**Issue by stefanbajic94** [TheAlgorithms/website#156]
### Description of the content report

https://the-algorithms.com/algorithm/singly-linked-list on this page the JS solution isn’t available but it’s implemented here https://github.com/TheAlgorithms/Javascript/blob/961f21f97c1ae53d79f90ee82a968d9a0409b968/Data-Structures/Linked-List/SinglyLinkList.js

### Additional information/context

Meta, I think the description of the content report field should be a text box, because a having a single line for long text makes it hard to scan and modify.

**Comment by maltejur** [comment]
Thanks for the report. I've opened a pull request in the JS repo to correct the name.

**Comment by maltejur** [comment]
> Meta, I think the description of the content report field should be a text box, because a having a single line for long text makes it hard to scan and modify.

I agree with that. @Panquesito7 could you take a look?

**Comment by maltejur** [comment]
Should be fixed now
