### ISSUE TITLE
[BUG] Plausible Analytics not working

### ISSUE THREAD

**Issue by Panquesito7** [TheAlgorithms/website#159]
### Description of the bug

The Plausible Analytics page is not working and displaying an error.
This issue has been for a long time by now. I thought it was fixed. 😅

Let me know if you need any help in fixing this. :)

### Add screenshots of the bug (if applicable)

![image](https://user-images.githubusercontent.com/51391473/155548221-5ed20a7f-ac40-40ff-9740-3164cbff5d89.png)

**Comment by maltejur** [comment]
Oh yep, thanks for reporting. I have moved the analytics to another server, everything is still a bit rough because of that. But it should work again now.

**Comment by Panquesito7** [comment]
Thanks for fixing it! 🎉
