### ISSUE TITLE
[BUG]: Many domains not being redirected

### ISSUE THREAD

**Issue by Panquesito7** [TheAlgorithms/website#16]
Many domains deployed with [Vercel](https://vercel.com) are not being redirected.
For example, see https://github.com/TheAlgorithms/website/commit/daed0a8c948ff0ffb217ceb68f6205b025d7bb95#commitcomment-47549040  and go to one of the links (except for the 3rd and the 4th).

**Comment by maltejur** [comment]
Those are just some weird domains vercel also gives a deployment. The only redirect I have configured is from thealgorithms.vercel.app to the-algorithms.com. As long as those other domains don't get shared, there is no need for redirects on them
