### ISSUE TITLE
[FEATURE] Customize scrollbar

### ISSUE THREAD

**Issue by raklaptudirm** [TheAlgorithms/website#161]
### Description of the feature request

The scroll-bar could be customized for a better overall look of the website.

**Comment by maltejur** [comment]
Hmm I don't see the advantage which that would bring. Imo that would probably just make the website more clunky. Custom scroll-bars also work somewhat different in different browsers.

**Comment by raklaptudirm** [comment]
I was thinking about nothing too special, just something matching the color theme.

**Comment by maltejur** [comment]
Hmm, the problem with that is that the CSS for changing the scrollbar color is different for every browser and a pain in the ass to get right, even for simple things like changing the color.

**Comment by raklaptudirm** [comment]
Chrome, Edge, Safari and Opera support the `::-webkit-scrollbar` pseudo element, which I believe should cover most major browsers.
![browsers](https://user-images.githubusercontent.com/68542775/156816496-69e5a650-dcc0-4ed0-a1f0-42eed7f772e0.PNG)

**Comment by maltejur** [comment]
But Firefox :( ...

**Comment by raklaptudirm** [comment]
I tested it. Looks like firefox has also added support for it :D

**Comment by raklaptudirm** [comment]
Well, for firefox it will just be the default scrollbar, so we are not losing anything. Or you could do [this](https://stackoverflow.com/questions/6165472/custom-css-scrollbar-for-firefox/54101063#54101063) and add support separately.

**Comment by maltejur** [comment]
Hmm, I've tested it out a bit on the [colored_scrollbar](https://github.com/TheAlgorithms/website/tree/colored_scrollbar) branch and it looks good in Firefox but pretty bad in chrome. Here's a preview: https://website-eipqoq7f6-thealgorithms.vercel.app/. So I would say we should just keep the native scrollbar which already looks pretty good imo (at least on Firefox/Linux). 

But do you maybe have some better colors/other styles which we could try which don't look as bad as mine in chrome?

**Comment by raklaptudirm** [comment]
They look the same in both the browsers to me though

Chrome:
![chromebar](https://user-images.githubusercontent.com/68542775/156893461-e0730358-6f78-4f48-b981-2c39a8fcba19.PNG)
Firefox:
![firefoxbar](https://user-images.githubusercontent.com/68542775/156893464-71507248-ff52-407c-95f2-8d772aeff273.PNG)

**Comment by maltejur** [comment]
Ah probably because Firefox actually respects how the native scrollbar looks.

**Comment by raklaptudirm** [comment]
Uh, so where does this leave us?

**Comment by maltejur** [comment]
Hm, imo the native scrollbar just looks better, especialy in the light mode

**Comment by raklaptudirm** [comment]
You can preserve the native look in light mode, but for dark mode I think we should change it.

**Comment by raklaptudirm** [comment]
Also, I suggest you make the actual scroller a light shade of gray like `#bbbbbb` in light mode.

**Comment by maltejur** [comment]
Hmm but even if we do that, I think the native scrollbar just looks better. In the custom scrollbar some key things are just missing, like the little arrows on the top and bottom, and the changing colors when you click or hover the scrollbar.

https://user-images.githubusercontent.com/48161361/156931408-0d417e07-e664-49f1-8020-efd63927b49b.mp4

**Comment by raklaptudirm** [comment]
I think we should do a poll in the server, see what everyone thinks, and then decide from that ¯\_(ツ)_/¯

**Comment by maltejur** [comment]
Sure

**Comment by raklaptudirm** [comment]
@maltejur 
![scrollbars](https://user-images.githubusercontent.com/68542775/158190236-d6c3c457-c1ab-4921-9b3a-b07a4e399a90.PNG)
