### ISSUE TITLE
[BUG] <Java  sorting pages not opting as mention in this issue #142>

### ISSUE THREAD

**Issue by AnujSsStw** [TheAlgorithms/website#167]
### Description of the bug

As mentioned in issue #142 (still open so I am contributing).  The java sorting GitHub page doesn't open for any sorting algorithm. 

## So the problem is this 
1. Code Implementation Links of java sorting link directs to this URL (I am using a bubble sort link for example)(https://github.com/TheAlgorithms/Java/blob/master/Sorts/BubbleSort.java)
2. The problem with this link is - it was supposed to be this (https://github.com/TheAlgorithms/Java/blob/master/src/main/java/com/thealgorithms/sorts/BubbleSort.java)

## The lib file is correct
![Screenshot (128)](https://user-images.githubusercontent.com/92370865/161818446-d791b20d-ed4a-4939-8ceb-30166a68df9a.png)

with java baseDir being (baseDir: "src/main/java/com/thealgorithms",)

## I think the problem comes from the Java repo itself because 👇
- If I see any other Code Implementation Links (example - Scala (https://github.com/TheAlgorithms/Scala/blob/master/src/main/scala/Sort/BubbleSort.scala) )
it works. it has the same baseDir thing as implemented in java - (based: "src/main/scala",)

Now try to compare both of the like (provided by web and repo link)- 
## web one - 
![Screenshot (131)](https://user-images.githubusercontent.com/92370865/161820042-d39717f2-98b3-4e5f-b2a0-beddcd87a080.png)

## repo one - 
![Screenshot (133)](https://user-images.githubusercontent.com/92370865/161820138-9fe90d8c-21dc-4a6d-b20c-b9f1c74881b2.png)

# So the only difference it comes down to is this 
## In the java repo of the sort folder notice how it is written in small letters 
![Screenshot (127)](https://user-images.githubusercontent.com/92370865/161820762-4c2a5d26-f503-420d-8718-8f00fd4eed81.png)
## as compared to other language repo of the sort folder (again taking the example of scala)
![Screenshot (134)](https://user-images.githubusercontent.com/92370865/161821102-42597b45-36f4-4f55-ad1a-73ea271c4dda.png)

### So maybe changing the java sort repo folder name from sort to Sort might work (i didn't read the whole codebase) because maybe it uses children prop.

PS I think for the test we can do that it's not going to affect the website in any way.

**Comment by maltejur** [comment]
As already mentioned in the other issue, the wrong hardcoded links are located in the [Algorithms-Explanation](https://github.com/TheAlgorithms/Algorithms-Explanation) repo.

**Comment by AnujSsStw** [comment]
OoO yes after going through it I see that. Thanks!
btw do I have to open separate pull requests for fixing different link locations or all in one?
