### ISSUE TITLE
[BUG] Missing algorithms

### ISSUE THREAD

**Issue by appgurueu** [TheAlgorithms/website#170]
### Description of the bug

Algorithms from the Lua repo are missing. See the [simplist radical form](https://github.com/TheAlgorithms/Lua/blob/main/src/math/simplist_radical_form.lua) algorithm for an example.

**Comment by appgurueu** [comment]
NVM, it has now appeared: https://the-algorithms.com/de/algorithm/simplist-radical-form

**Comment by maltejur** [comment]
Yeah, the website just wasn't built new since you renamed/created that file, so I just started a rebuild.

**Comment by appgurueu** [comment]
> Yeah, the website just wasn't built new since you renamed/created that file, so I just started a rebuild.

Do you have to manually start rebuilds every time? Does it not rebuild daily?

**Comment by maltejur** [comment]
It doesn't rebuild automatically but that pretty much wasn't a problem so far because there are always new commits at least once a week which trigger a rebuild.

**Comment by appgurueu** [comment]
> It doesn't rebuild automatically but that pretty much wasn't a problem so far because there are always new commits at least once a week which trigger a rebuild.

Please make it rebuild when any of the algorithm repos has a new commit, with at least daily frequency.

**Comment by maltejur** [comment]
It takes ~20 minutes to build the website so daily rebuilds would be a bit wasteful. Would you say a weekly rebuild would be enough or should it be more often?

**Comment by appgurueu** [comment]
> It takes ~20 minutes to build the website so daily rebuilds would be a bit wasteful. Would you say a weekly rebuild would be enough or should it be more often?

How about every two days? 10 minutes per day is acceptable IMO.

**Comment by maltejur** [comment]
Ok, I'll do that

**Comment by maltejur** [comment]
With https://github.com/TheAlgorithms/website/blob/main/.github/workflows/redeploy.yml it should now redeploy every two days
