### ISSUE TITLE
[FEATURE] Translating into Japanese

### ISSUE THREAD

**Issue by ShisatoYano** [TheAlgorithms/website#178]
### Description of the feature request

Hi. I'm Shisato Yano from Japan.  
I found this project and it looks so great!!  

I'd like to suggest to add function translating all sentences into Japanese on your website. I think that a lot of Japanese programmers are interested in this project and it's very useful for them to translate into Japanese.  

If above my suggestion is also valuable for you guys, I will try contributing to this project by translating by myself. Is it OK?

**Comment by maltejur** [comment]
> If above my suggestion is also valuable for you guys, I will try contributing to this project by translating by myself. Is it OK?

Definitely, it would be really great if you could provide the translations. You can add them yourself here: https://hosted.weblate.org/engage/TheAlgorithms/.

**Comment by ShisatoYano** [comment]
Thank you for agreeing my suggestion.  
I will try translating.

**Comment by Panquesito7** [comment]
Closing as anyone can easily add translations and contribute directly on [Weblate](https://hosted.weblate.org/projects/TheAlgorithms/common/).
