### ISSUE TITLE
[OTHER] Replace all `discord.gg` links with the new link

### ISSUE THREAD

**Issue by Panquesito7** [TheAlgorithms/website#181]
### What would you like to share?

We now have a link to our Discord server using our domain, which is much easier to remember and share.
All `discord.gg` instances should be replaced with `https://the-algorithms.com/discord/`.

### Additional information/context

This is a good first issue. Please leave it open to beginners or first-time contributors. 🙂

**Comment by techsnap** [comment]
Hey @Panquesito7, I am a beginner and would like to work on this. Can you assign this to me?
