### ISSUE TITLE
[BUG] Discord link not working after a few times

### ISSUE THREAD

**Issue by Panquesito7** [TheAlgorithms/website#185]
### Description of the bug

On Microsoft Edge Chromium, after using the `https://the-algorithms.com/discord/` link, it appears it is not letting me join the Discord server, as the website has redirected me way too many times.
It suggests you clean up the website cookies, which I've tried, but it doesn't seem to work.

Does this happen to you as well? Let us know below.

### Add screenshots of the bug (if applicable)

![image](https://user-images.githubusercontent.com/51391473/192418295-3b0fcfb6-2885-4b22-89f3-f7f3b1a2e427.png)

**Comment by anuragts** [comment]
@Panquesito7 this is happening with me also, on both brave and edge browsers.

**Comment by Vaibhav13kamat** [comment]
assign me this issue ..also what's the link to the Discord server?

**Comment by Panquesito7** [comment]
Found the issue that is causing that. Here we must use the Discord invitation link instead (my bad).

https://github.com/TheAlgorithms/website/blob/f3d6dc73da3c9016f75767c71fb1e5af3ca83b33/pages/%5Bshortlink%5D.tsx#L6-L11

Let me know if you wanna work on this. Thanks. 🙂

**Comment by Vaibhav13kamat** [comment]
yes sure
