### ISSUE TITLE
[FEATURE] Enhancing search bar and page

### ISSUE THREAD

**Issue by ghost** [TheAlgorithms/website#188]
### Description of the feature request

 Adding loader while loading for search and making search bar even more engaging

### Add screenshots of the feature request (if applicable)

![Screenshot (136)](https://user-images.githubusercontent.com/113957926/193401065-d10e10cc-f112-4a54-a115-01aedca942dd.png)

**Comment by maltejur** [comment]
There already is a loader at the top of the page

**Comment by Panquesito7** [comment]
Hmm, one thing I noticed is that the search bar doesn't show up until you scroll down.

Here it doesn't show up.
![image](https://user-images.githubusercontent.com/51391473/193435724-6c25a651-6f6a-40fa-b696-f69dd716a293.png)

While here it _does_ show up.
![image](https://user-images.githubusercontent.com/51391473/193435747-05e4b3b4-b044-4c73-8693-dd463d71bd10.png)

Not sure if this is the same issue, though.

**Comment by maltejur** [comment]
@Panquesito7 
![image](https://user-images.githubusercontent.com/48161361/193454937-860639f1-7614-4677-b6de-66d25b016082.png)

**Comment by Vivek-04022001** [comment]
Hey, I'm interested in this issue. Can I contribute to it?

**Comment by maltejur** [comment]
Sure

**Comment by xgovernor** [comment]
Is this problem solved?  if not, can i try? otherwise close the issue

**Comment by maltejur** [comment]
I am not really sure what the issue is here, but if you find something you can do, sure.
