### ISSUE TITLE
[OTHER] Cannot access website

### ISSUE THREAD

**Issue by pea-sys** [TheAlgorithms/website#192]
### What would you like to share?

Cannot access website
I had access to it until yesterday.
I accessed the site with two PCs in different network environments and the results were the same.
I cleared my browser's cache and could not access the site.

https://the-algorithms.com/

**Comment by maltejur** [comment]
@AnupKumarPanwar the domain seems to be misconfigured

![image](https://user-images.githubusercontent.com/48161361/193557461-43b40a4e-dd50-4f78-bf9a-6dc8233b2718.png)

**Comment by data-djinn** [comment]
is it possible the domain has expired?
<img width="789" alt="image" src="https://user-images.githubusercontent.com/56449985/194200981-4d67e732-8871-436d-8622-98cf992abce5.png">

**Comment by pea-sys** [comment]
I can access the website now

**Comment by data-djinn** [comment]
Same, issue seems to be resolved
