### ISSUE TITLE
Two separate entries for XOR Cipher

### ISSUE THREAD

**Issue by SpiderMath** [TheAlgorithms/website#193]
### Description of the content report

I found 2 separate entries for XOR Cipher, one having Py, JS, C++, PHP implementations and the other having Go and Rust implementations

### Add screenshots of the content report (if applicable)

![image](https://user-images.githubusercontent.com/71999854/194395414-31408afd-cdce-4ec6-8d6f-bf0e55e5838c.png)

### Additional information/context

Links to the entries:
- [Go & Rust](https://the-algorithms.com/algorithm/xor)
- [JS, Py, PHP, C++](https://the-algorithms.com/algorithm/xor-cipher)

**Comment by maltejur** [comment]
Fixed in https://github.com/TheAlgorithms/website/commit/b5f8ee0e65288bd46c25f47fc0171c4aed80a781
