### ISSUE TITLE
No TypeScript results on website

### ISSUE THREAD

**Issue by SpiderMath** [TheAlgorithms/website#194]
![Screenshot from 2022-10-07 00-09-51](https://user-images.githubusercontent.com/71999854/194394334-1001d9a2-4555-4e0a-a9e7-c915dc32d1b6.png)
Despite having a binary convert implementation on the TypeScript repository, I don't see anything on the website. Same for the other algorithms added in here. 
Even the link given to the [site](https://the-algorithms.com/language/typescript) gives a 404 :no_mouth:

**Comment by appgurueu** [comment]
I believe the site hasn't been updated yet. That's an issue for the site repo.

**Comment by Panquesito7** [comment]
The language must be added to the languages list for the website.
To add TypeScript to the list, follow the next steps:

1. Go to `lib/repositories.ts`.
2. After `Lua`, add a new field with the following content:

```ts
  typescript: {
    name: "TypeScript",
    allowedFiles: [".ts"],
    baseDir: "./",
  },
```

3. Save the file and then go to `components/icon/index.tsx`.
4. After the `lua` case, insert a new case:

```tsx
case "typescript":
    return icon("typescript", colored ? "original" : "plain");
```

5. Commit your changes, push, and make a [**pull request**](https://github.com/TheAlgorithms/website/compare).
6. That's it! You've made a PR 🎉 You need to wait until a maintainer reviews your PR. 🙂

Any further help you need, let us know!
