### ISSUE TITLE
Four entries for Armstrong Number

### ISSUE THREAD

**Issue by SpiderMath** [TheAlgorithms/website#196]
### Description of the content report

I found 4 entries for 'armstrong', all of which are for the same thing but for different languages.

### Add screenshots of the content report (if applicable)

![image](https://user-images.githubusercontent.com/71999854/194706574-bc661e29-356d-4b70-af5c-3351470fb1b0.png)

### Additional information/context

The links to the entries are:
- https://the-algorithms.com/algorithm/armstrong-number
- https://the-algorithms.com/algorithm/armstrong-numbers
- https://the-algorithms.com/algorithm/armstrong
- https://the-algorithms.com/algorithm/is-armstrong

**Comment by maltejur** [comment]
Fixed in https://github.com/TheAlgorithms/website/commit/b0f602e899597113edb4e32a39d50abf5e76e1e7
