### ISSUE TITLE
[FEATURE] Add the Bengali language

### ISSUE THREAD

**Issue by Panquesito7** [TheAlgorithms/website#207]
### Description of the feature request

The Bengali language is already added to Weblate. We just need to adopt it in our code to make it work properly.

**Steps to contribute:**

_If you've already forked the repository, skip to step 3_

1. Fork the repository [here](https://github.com/TheAlgorithms/website/fork).
2. Make a new branch named `add_bengali`.
3. Open the `lib/locales.js` file.
4. After the Portuguese (`pt_BR`) language, add the following code:

```js
  {
    name: "বাংলা",
    code: "bn",
    icon: "bangladesh",
  },
```

5. You will need to add a flag icon under [`public/flags`](https://github.com/TheAlgorithms/website/tree/main/public/flags). For this, we will use the Bangladesh flag. You can take it from here: https://upload.wikimedia.org/wikipedia/commons/f/f9/Flag_of_Bangladesh.svg

6. Open a [pull request](https://github.com/TheAlgorithms/website/compare).
7. That's it! You need to wait until a maintainer reviews your PR. 🎉

If you need any help you need, let us know below or on our [Discord server](https://the-algorithms.com/discord)!

### Additional information/context

This is a good first issue. Please leave it open to first-time contributors and beginners.

**Comment by SO-HYBE** [comment]
I will do it assign me

**Comment by SO-HYBE** [comment]
I'm done and I'm waiting for the reviewer to accept my pr.
