### ISSUE TITLE
Mobile Responsive Title Bar issue

### ISSUE THREAD

**Issue by Yashank18** [TheAlgorithms/website#21]
I was looking around the website, found that in mobile view the logo of the website comes over the sidebar and it looks kind of weird whereas on the other page it works fine.

Adding a few Screenshot for the refernce  :)

Homepage :

![Screenshot (282)](https://user-images.githubusercontent.com/46098062/109645597-1518b000-7b7d-11eb-967f-a700bf6d7d3f.png)

Other pages:
![Screenshot (283)](https://user-images.githubusercontent.com/46098062/109645582-121dbf80-7b7d-11eb-8071-c45325e9289e.png)

**Comment by maltejur** [comment]
Thanks for pointing out! Fixed in 6ee1b167c31449330a4dc9836f54e9cde8af34fd
