### ISSUE TITLE
Duplicate entries for Euler's Totient 

### ISSUE THREAD

**Issue by SpiderMath** [TheAlgorithms/website#218]
### Description of the content report

I recently found four entries for the implementation of the Euler's totient function

### Add screenshots of the content report (if applicable)

![image](https://user-images.githubusercontent.com/71999854/216776465-64031ce3-459c-4e38-9968-cc71c7cb3e3e.png)

### Additional information/context

The entries are (as shown in order of the screenshot): 
- https://the-algorithms.com/algorithm/eulers-totient
- https://the-algorithms.com/algorithm/eulers-totient-function
- https://the-algorithms.com/algorithm/eulertotient
- https://the-algorithms.com/algorithm/a000010-eulers-totient

There also seem to be two implementations in the [JavaScript](https://github.com/TheAlgorithms/JavaScript) repository, so I would like to urge the repository maintainers to remove one of the implementations (I'm not sure if I'm to open an issue for this in that repository as well, so I'm currently not doing so).

**Comment by Panquesito7** [comment]
> There also seem to be two implementations in the [JavaScript](https://github.com/TheAlgorithms/JavaScript) repository...

You should create an issue in the JavaScript repository in that case.
