### ISSUE TITLE
[BUG] Invalid github link

### ISSUE THREAD

**Issue by Complexlity** [TheAlgorithms/website#228]
### Description of the bug

On [Arrray Queue algorithm](https://the-algorithms.com/algorithm/array-queue), the `View on Github` icon goes to [page not found](https://github.com/TheAlgorithms/typescript/tree/master/data_structures/array_queue.ts). I found out this is [the correct link](https://github.com/TheAlgorithms/TypeScript/blob/master/data_structures/queue/array_queue.ts).

### Additional information/context

I look around this website repository to find out how to fix it and open a PR but wasn't sure where to replace the link. So I ask that someone should tag me when they create a PR for the solution so I'd learn from it

**Comment by Complexlity** [comment]
**Update**: I found it had to do with [this PR](https://github.com/TheAlgorithms/TypeScript/pull/113) made 5 hours ago on the TypeScript repository. It grouped the algorithms in the [Data structures folder](https://github.com/TheAlgorithms/TypeScript/tree/master/data_structures) and this makes all the `View on Github` links on the `typescript data structures` section no longer work
<br/>
![typescript data structures](https://user-images.githubusercontent.com/105590967/224854107-292065d6-127b-4393-a7be-587f20249ed6.png)
![image](https://user-images.githubusercontent.com/105590967/224854524-a270ca7e-2428-4896-b5f5-a22a5c63f188.png)

**Comment by maltejur** [comment]
Since this was just a content change, I've rebuilt the site and it seems to be fixed now.
