### ISSUE TITLE
[FEATURE] Show implementation in language X when coming from list of algorithms in language X

### ISSUE THREAD

**Issue by dlesnoff** [TheAlgorithms/website#238]
### Description of the feature request

Currently,
when coming from the URL https://the-algorithms.com/language/nim and clicking on an algorithm, the showed implementation is always the Python one.

It seems logical that the Nim implementation like this one https://the-algorithms.com/algorithm/viterbi?lang=nim appears instead.of https://the-algorithms.com/algorithm/viterbi?lang=python by default.

**Comment by maltejur** [comment]
Good idea, implemented in https://github.com/TheAlgorithms/website/commit/03dd7a9b116d317a15c1447f8d137353f15b32a5
