### ISSUE TITLE
[BUG] Paragraphs and headlines not aligned correctly in Arabic version

### ISSUE THREAD

**Issue by MuhammadRabi** [TheAlgorithms/website#251]
### Description of the bug

**Description of the bug**
Arabic paragraphs and section headlines are misaligned in the Arabic version.

**How to reproduce**
Change the language in the translation button to Arabic

**Expected behavior**
Arabic paragraphs and section headlines text should be aligned right.

**Screenshots**
![Paragraph-ar-alignment-02](https://github.com/TheAlgorithms/website/assets/34184092/e0056ba6-2415-4ee8-9efc-4a91971e5877)
![Paragraph-ar-alignment](https://github.com/TheAlgorithms/website/assets/34184092/0ab9823f-5072-4c62-8043-c0b24cb70f67)

### Add screenshots of the bug (if applicable)

![Paragraph-ar-alignment](https://github.com/TheAlgorithms/website/assets/34184092/0ab9823f-5072-4c62-8043-c0b24cb70f67)

**Comment by ahmed0saber** [comment]
Hello @MuhammadRabi , glad to meet you here!

Hello @Panquesito7 , hope you are doing well!
I have worked on the issue and provided a solution within my pull request #285, can you review it?

Thank you in advance.

**Comment by MuhammadRabi** [comment]
> Hello @MuhammadRabi , glad to meet you here!
> 

Hi @ahmed0saber, I'm always happy to see you too. Really appreciate your contribution on PR #285 You've done a fantastic work. 

Have a great day!
