### ISSUE TITLE
[BUG] The search bar shows results even if the input is empty.

### ISSUE THREAD

**Issue by ESAM-ALSAWAH** [TheAlgorithms/website#253]
### Description of the bug

When I search, then remove the content from the input, it shows the result for the first character in the input.

### Add screenshots of the bug (if applicable)

https://github.com/TheAlgorithms/website/assets/86329891/7e9b28f8-75bc-4c02-9e7e-632aa683a14c

**Comment by ankit1016** [comment]
anyone is working on this issue?

**Comment by ESAM-ALSAWAH** [comment]
Yes I already worked on it and it is solved #254.

**Comment by Ayush17112002** [comment]
@ESAM-ALSAWAH, it is still showing the results on empty search bar, is your PR not merged yet?
