### ISSUE TITLE
Bug: Navigation Bar is not seeing properly

### ISSUE THREAD

**Issue by BamaCharanChhandogi** [TheAlgorithms/website#258]
### Description

In light mode when you scroll down your page you must see this error.

**System Requirements:**

_OS: Microsoft Edge
Device: Laptop/Computer_

### Expected Behavior

You will see white color

### Actual Behavior

If you are in dark mode you will not see this issue.

### Steps to reproduce (if applicable)

1. open this website https://the-algorithms.com/
2. Scroll down

**Comment by appgurueu** [comment]
@Panquesito7 could you please transfer this issue to https://github.com/TheAlgorithms/Website?

**Comment by ghost** [comment]
Hi, The light mode isn't working on Microsoft Edge. (changes to grayish color instead of white). Did I understand it right?

I would like to work on this issue. I am new to open source and first time contributing to hacktoberfest. Let me know if I need any prerequisites to work on this issue.

**Comment by Panquesito7** [comment]
> Hi, The light mode isn't working on Microsoft Edge. (changes to grayish color instead of white). Did I understand it right?
> 
> I would like to work on this issue. I am new to open source and first time contributing to hacktoberfest. Let me know if I need any prerequisites to work on this issue.

I think the author's trying to say that the navbar color is gray in light mode, and when scrolling down, it should look white. I'm not sure if this is a bug or something we should change, though. IMO, it looks fine as-is. Closing this issue for now.

Feel free to clarify if I'm wrong. 🙂
