### ISSUE TITLE
Icon Misleading

### ISSUE THREAD

**Issue by ayaankhan98** [TheAlgorithms/website#26]
It must be replaced by dart icon.

![Capture](https://user-images.githubusercontent.com/43348292/110242146-b5564680-7f7a-11eb-9d26-6459391fc646.JPG)

**Comment by maltejur** [comment]
The dart icon wasn't available on devicons when I first added the icons, so i opened a PR https://github.com/devicons/devicon/pull/522 and added it. It already got merged, we will just have to wait until the next npm release of devicons, then I will update it here.

**Comment by ayaankhan98** [comment]
> The dart icon wasn't available on devicons when I first added the icons, so i opened a PR [devicons/devicon#522](https://github.com/devicons/devicon/pull/522) and added it. It already got merged, we will just have to wait until the next npm release of devicons, then I will update it here.

Okay, Thanks for informing.
