### ISSUE TITLE
Add contributors to algorithm page

### ISSUE THREAD

**Issue by maltejur** [TheAlgorithms/website#27]
A good idea would be to include contibutors of the code on the page, like github does. Example:
![Screenshot 2021-03-19 200721](https://user-images.githubusercontent.com/48161361/111830833-cb56f600-88ee-11eb-9082-f8b0d4b94efe.png)

**Comment by Panquesito7** [comment]
Sounds good to me. 👍

**Comment by maltejur** [comment]
I didn't find any practical way to do this via the github api (only via graphql, but the quota there is too low for all the pages), so I am closing this. If anybody finds a good way to do this via the github api, just write here and I will reopen.
