### ISSUE TITLE
[BUG] Search Bar not Working on Safari

### ISSUE THREAD

**Issue by cyrixninja** [TheAlgorithms/website#271]
### Description of the bug

The search feature not working at all on iOS devices. I have tried it on Android and it works fine but never on my iPhone or iPad.

### Add screenshots of the bug (if applicable)

Here the Video of the Bug [Video](https://youtube.com/shorts/gdrdaeE7n-g)

**Comment by maltejur** [comment]
Thanks for the report, this should be fixed in https://github.com/TheAlgorithms/website/commit/059a8dd6d5fc4bcac7930aae5c05a0051b10bb70
