### ISSUE TITLE
[BUG] Rust Icon on Website Broken

### ISSUE THREAD

**Issue by cyrixninja** [TheAlgorithms/website#277]
### Description of the bug

Rust Icon on Website is  Broken. Can't see the Rust Logo on Website

### Add screenshots of the bug (if applicable)

![Screenshot 2023-12-07 083907](https://github.com/TheAlgorithms/website/assets/61012869/f74075a2-39a6-43c2-bba3-06dc09a5310f)
![Screenshot 2023-12-07 084143](https://github.com/TheAlgorithms/website/assets/61012869/50f0d0dc-e450-4f96-b4a2-a3dbc300e016)

**Comment by Somnath-sanu** [comment]
its clearly showing .

**Comment by maltejur** [comment]
Thanks, it seems like https://github.com/devicons/devicon/pull/2029 broke this. Should be fixed through https://github.com/TheAlgorithms/website/commit/aee75cdf0728d3b44f2544a5c693319be30064ad.
