### ISSUE TITLE
The unusual behaviour of the Search bar

### ISSUE THREAD

**Issue by Jils31** [TheAlgorithms/website#296]
### Description of the bug

In the search bar which is on the main page in the header section, when user enters any letter before completing the whole word the website starts showing the result which affects the user experience thus the feature of completing the word and then showing the result should be added.

### Add screenshots of the bug (if applicable)

https://github.com/user-attachments/assets/9623913e-b54e-4f04-9639-5af5a04bc54a

**Comment by aman124598** [comment]
Please assign this issue to me

**Comment by maltejur** [comment]
This is working as expected
