### ISSUE TITLE
Add the ability to change to dark/light mode

### ISSUE THREAD

**Issue by Panquesito7** [TheAlgorithms/website#4]
It would be cool if there'd be an option to make the website be in dark mode.
For example, I use [Dark Reader](https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh), and it looks pretty cool in Dark Mode:

![Website using Dark Reader](https://user-images.githubusercontent.com/51391473/107904526-ad722c00-6f11-11eb-9772-1a778bea5592.png)

**Comment by maltejur** [comment]
Should be relatively easy to do using [material uis theming system](https://material-ui.com/customization/theming/#theming). I already use this for the big jumbo on the home page, and it looks like this
```jsx
<DarkThemeProvider>
  <div className={classes.outer}>
    <div className="container">
      <Typography className={classes.h1}>Hello, algorithms!</Typography>
      <Typography className={classes.h2}>
        Welcome to GitHub's largest open-source algorithm library
      </Typography>
      <div className={classes.input}>{search}</div>
    </div>
  </div>
</DarkThemeProvider>
```
```jsx
import React from "react";
import { createMuiTheme, ThemeProvider } from "@material-ui/core/styles";

const darkTheme = createMuiTheme({
  palette: {
    type: "dark",
    primary: {
      main: "#fff",
    },
  },
});

export default function DarkThemeProvider({ children }) {
  return <ThemeProvider theme={darkTheme}>{children}</ThemeProvider>;
}
```

You would just need to put the DarkThemeProvider in the _app component and add a switch. I quickly tried that and it looks pretty good, it just needs some tweaking at some points.

![Screenshot_2021-02-15 The Algorithms](https://user-images.githubusercontent.com/48161361/107924130-c232dc00-6f72-11eb-88c0-1d069975f835.png)
![Screenshot_2021-02-15 Quick Sort - The Algorithms](https://user-images.githubusercontent.com/48161361/107924134-c3640900-6f72-11eb-9625-4b64fb8ecf68.png)

**Comment by maltejur** [comment]
832234466f701a72c52baab765d9e9b151eb6cb2
