### ISSUE TITLE
Use icons for all languages like MATLAB-Octave

### ISSUE THREAD

**Issue by Panquesito7** [TheAlgorithms/website#7]
All repositories have an image, but there are some repositories
that are missing an image, such as the [MATLAB-Octave](https://gihtub.com/TheAlgorithms/MATLAB-Octave) repository.

**Comment by maltejur** [comment]
I use the [devicons](https://github.com/devicons/devicon) library for the other languages, so it will probably be the best idea just to add icons for the languages there and then just use them here.

**Comment by Panquesito7** [comment]
Working on it. Thank you. 🙂

**Comment by Panquesito7** [comment]
https://github.com/devicons/devicon/pull/492

**Comment by maltejur** [comment]
Just keeping track of which icons are still missing
- [x] R https://github.com/devicons/devicon/pull/491
- [x] Matlab https://github.com/devicons/devicon/pull/492
- [x] F# https://github.com/devicons/devicon/pull/495
- [x] AArch64 Assembly https://github.com/devicons/devicon/pull/507
- [x] Jupyter https://github.com/devicons/devicon/pull/501
- [x] Ocaml https://github.com/devicons/devicon/pull/502
- [x] Elixir https://github.com/devicons/devicon/pull/500

I will also open some PRs there

**Comment by Panquesito7** [comment]
Jupyter: https://github.com/devicons/devicon/pull/501

**Comment by Panquesito7** [comment]
OCaml: https://github.com/devicons/devicon/pull/502

**Comment by Panquesito7** [comment]
I'm working on the logo for AArch64 Assembly. 🙂

**Comment by Panquesito7** [comment]
AArch64 Assembly: https://github.com/devicons/devicon/pull/507

**Comment by Panquesito7** [comment]
https://github.com/maltejur/thealgorithms/commit/e70b9539246fadd38d2d193c49656b17d44167c9
