### ISSUE TITLE
Untranslated string

### ISSUE THREAD

**Issue by milotype** [TheAlgorithms/website#73]
Title for **All algorithms** on https://the-algorithms.com/hr/all does not translate. The title seems to be hard coded, because other languages have the same problem.

I'm not a programmer, but I think something needs to be changed in the file website/pages/all.tsx, so the translated string in Weblate gets used, just as it does in the website's footer (please see attached screenshots).

![ AllAlgorithms](https://user-images.githubusercontent.com/43657314/118364178-a2be4600-b597-11eb-9d10-aa88d7bcc53d.png)

![footer](https://user-images.githubusercontent.com/43657314/118364526-0dbc4c80-b599-11eb-99c6-ed19c3511c75.png)

**Comment by maltejur** [comment]
Fixed in 63130b3
