### ISSUE TITLE
Add Analytics

### ISSUE THREAD

**Issue by maltejur** [TheAlgorithms/website#79]
chetan:
> Yes, let's add it. This way atleast we could know how many people are using the website also what all features are most used and focus on them.

I wouldn't use google analytics, but something simpler like [plausible](https://plausible.io/) which could also be self-hosted.

**Comment by dynamitechetan** [comment]
Is plausible paid?

**Comment by maltejur** [comment]
If you use their hosted version, yes. But I am trying to set it up myself right now

**Comment by maltejur** [comment]
Okay, everything should be set up. Let's see if it works

**Comment by AnupKumarPanwar** [comment]
For self-hosted plausible, we need to pay for our hosting, right? If adding google analytics is more complex, I'll get a Digital Ocean server for this. Let me know your thoughts. Although the dashboard looks quite clean and beautiful.

**Comment by maltejur** [comment]
I can host it myself, it doesn't require much. It would be nice for me tho to have access to the domain. Can you set the nameservers to vercel, so I can add my server there under our domain? They are:
```
ns1.vercel-dns.com
ns2.vercel-dns.com
```

**Comment by dynamitechetan** [comment]
@AnupKumarPanwar can you update these nameservers please?

**Comment by AnupKumarPanwar** [comment]
@maltejur If I change the Nameservers then the current DNS records would get invalidated, which will affect our mail exchange and we might also lose the verified badge on Github. You can tell me the DNS records that you want to add.

**Comment by maltejur** [comment]
Set plausible.the-algorithms.com to 116.203.248.82.

**Comment by AnupKumarPanwar** [comment]
Done. Propagation might take some time.

**Comment by maltejur** [comment]
Okay, everything is set up. The analytics are now reachable under https://plausible.the-algorithms.com/the-algorithms.com
