### ISSUE TITLE
Regex Mismatch for algorithm explanation

### ISSUE THREAD

**Issue by Kunal-2001** [TheAlgorithms/website#91]
Can you explain what this regex expression is supposed to do? This is returning null value for every file due to which code inside the "if" block is not getting executed. 

`          const match = dir.match(/(?:.+)\/(.+)\.md/);`

**Comment by maltejur** [comment]
It is supposed to check if a markdown file is in a valid path and gets the filename. It seems like the issue is because of the windows path backslashes. I'll try to fix that.

**Comment by maltejur** [comment]
Can you check if ba7cd626cc26fa49d86c401d91930cb599fc83fc fixed it for you?

**Comment by Kunal-2001** [comment]
@maltejur Actually I have switched to linux, So I am not sure for windows but for me it's working now.
