### ISSUE TITLE
Add more Programming Languages to Code Playground

### ISSUE THREAD

**Issue by ayaankhan98** [TheAlgorithms/website#96]
Idea is to add a code playground section in code view frame. Once user clicks on `Play` button, user should be able to modify a virtual instance of current code and should be able to play around with that code by running the modified code on the very same page. This will create a beautiful learning experince.

- [ ] C (High Priority)
- [ ] C++ (High Priority)
- [ ] Java (High Priority)
- [x] Python (High Priority)
- [ ] Javascript (High Priority)
- [ ] Rust (Medium Priority)
- [ ] Golang (Medium Priority)
- [ ] MATLAB (Low Priority)
- [ ]  Ruby (Low Priority)
- [ ] C# (High Priority)
- [ ] Swift (Medium Priority)
- [ ] Jupyter (Medium Priority)
- [ ] Julia (Low Priority)
- [ ] Kotlin (High Priority)
- [ ] R (Medium Priority)
- [ ] OCaml (Low Priority)
- [ ] Elm (Low Priority)
- [ ] Dart (Medium Priority)
- [ ] Haskell (Medium Priority)
- [ ] Elixir (Low Priority)
- [ ] Clojure (Low Priority)
- [ ] F# (Low Priority)
- [ ] Scala (Low Priority)
- [ ] PHP (Low Priority)
- [ ] AArch-64 Assembly (Low Priority)

**Comment by maltejur** [comment]
This sounds like a great idea, but pretty hard to implement securely. I know somebody who did something similar like this in a project, so I will talk to him about this.

**Comment by maltejur** [comment]
As I see it there are 3 options to do this

- Run the code on a server (would probably work the best, but could be unsecure if done incorrect)
- Use some sort of Web Assembly library to run the code directly in the browser
- Transpile every language to javascript and run that (if that even is possible)

**Comment by ayaankhan98** [comment]
> As I see it there are 3 options to do this
> 
> * Run the code on a server (would probably work the best, but could be unsecure if done incorrect)
> * Use some sort of Web Assembly library to run the code directly in the browser
> * Transpile every language to javascript and run that (if that even is possible)

Let's discuss about this on discord.

**Comment by KukretiShubham** [comment]
Can anyone tell how this can be done? Does it require compiler engine?

**Comment by maltejur** [comment]
> Can anyone tell how this can be done? Does it require compiler engine?

I have implemented a approach with [pyodide](https://pyodide.org/en/stable/), which uses web assembly to run the code in the browser.

**Comment by ayaankhan98** [comment]
> > Can anyone tell how this can be done? Does it require compiler engine?
> 
> I have implemented a approach with [pyodide](https://pyodide.org/en/stable/), which uses web assembly to run the code in the browser.

Sounds good.
Other simple way is to use firepad editor.

**Comment by Panquesito7** [comment]
I'll re-open this as it's only implemented for Python and not for all the languages provided. 🙂
